services:
  employeedb:
    image: mcr.microsoft.com/mssql/server

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.2

  messagebroker:
    image: rabbitmq:management

  redarbor.technicaltest.api:
    image: ${DOCKER_REGISTRY-}redarbortechnicaltestapi
    build:
      context: .
      dockerfile: src/Redarbor.TechnicalTest.Api/Dockerfile